spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    s3:
      bucket: kgu6
    stack:
      auto: false